### PR TITLE
hyprland/workspaces: Improve the workspaces persistency logic

### LINKED ISSUE #2945: hyprland/workspaces: Persistent workspace disappear after being active
Hi,
With commit 11310b89f063a305de0d23aa4dd21d6ef365a776, a workspace set as persistent is not shown anymore after being active and then destroyed by Hyprland.

Config:
```
    "hyprland/workspaces": {
        "all-outputs": true,
        "format": " {icon}",
        "persistent-workspaces": {
            "*": [1, 2, 3, 4, 5, 6, 7, 8]
        },
    },
```

How to reproduce:

1. Start waybar with persistent workspaces. All persistent workspaces are shown correctly at start. Using my config above, it'll show this: <br/>20240220_22h51m34s_grim
2. Switch to a an empty workspace in Hyprland, set as persistent in waybar. For example, switching to `i`, it works as intended: <br/>20240220_22h51m51s_grim
3. Switch to another workspace in Hyprland. Workspace `i` is destroyed in Hyprland, and not persistent anymore in Waybar (it is not listed anymore): <br/>20240220_22h52m04s_grim

Reverting commit 11310b89f063a305de0d23aa4dd21d6ef365a776 fixes this behavior.
CC @zjeffer for the #2603.

Edit: I forgot to specify that I don't set my workspaces as persistent in Hyperland, only in Waybar.

### PR DESCRIPTION
**Pull request by aruhier**
Fixes #2945

Split the config and rule persistency in 2 attributes, one storing the persistency as set in Waybar's config, the other one storing the persistency as set in Hyprland.

It fixes some conflicts between the persistency state of a workspace as set in Waybar's config and its dynamic state in Hyprland.

It allows to remove a persistent workspace in Waybar if this workspace is removed from Hyprland and if the workspace is not set as persistent in Waybar's config.

### CODE REVIEW

**Comment by aruhier** [comment]
CC @zjeffer

**Review by zjeffer — APPROVED** [review]
Works really well! Thanks!

File: include/modules/hyprland/workspaces.hpp [hunk 1]
```diff
@@ -70,14 +70,16 @@ class Workspace {
   std::string output() const { return m_output; };
   bool isActive() const { return m_isActive; };
   bool isSpecial() const { return m_isSpecial; };
-  bool isPersistent() const { return m_isPersistent; };
+  bool isPersistent() const { return m_isPersistentRule || m_isPersistentConfig; };
+  bool isPersistentConfig() const { return m_isPersistentConfig; };
```
Comment (zjeffer) [inline include/modules/hyprland/workspaces.hpp:74]: For consistency, maybe you could also add an `isPersistentRule()` function that returns the `m_isPersistentRule` boolean.

File: include/modules/hyprland/workspaces.hpp [hunk 2]
```diff
@@ -101,7 +103,10 @@ class Workspace {
   uint m_windows;
   bool m_isActive = false;
   bool m_isSpecial = false;
-  bool m_isPersistent = false;
+  // m_isPersistentRule represents the persistent state in hyprland
+  bool m_isPersistentRule = false;
+  // m_isPersistentConfig represents the persistent state in the Waybar config
+  bool m_isPersistentConfig = false;
```
Comment (zjeffer) [inline include/modules/hyprland/workspaces.hpp:109]:
```suggestion
  bool m_isPersistentRule = false; // represents the persistent state in hyprland
  bool m_isPersistentConfig = false; // represents the persistent state in the Waybar config
```

**Review by zjeffer — APPROVED** [review]
Some nitpicking ;)

File: include/modules/hyprland/workspaces.hpp (hunk 1 above)
Comment (aruhier) [reply include/modules/hyprland/workspaces.hpp:74]: Done. I didn't add it initially as it's not used and is a getter easy to add.

**Comment by aruhier** [comment]
Thanks for the review!

**Comment by Alexays** [comment]
LGTM, thanks guys!
