### PR TITLE
disable Idle Inhibitor module if unsupported

### LINKED ISSUE #973: Crash when idle inhibit protocol is not supported
Waybar crashes when compositor doesn't support idle inhibit protocol and the module is clicked. Here's everything it dumped to console although only the last line is really relevant. I also opened a [issue for river to support the protocol](https://github.com/ifreund/river/issues/199), but it might take some time and it would be nice not to crash but print something usefull to logs, so the issue is easier to debug for end user.

```
$ waybar --log-level trace
[2021-01-12 23:27:23.748] [info] Resources files: /home/rasmus/.config/waybar/config, /etc/xdg/waybar/style.css
[2021-01-12 23:27:23.761] [debug] Output detected: eDP-1 (Chimei Innolux Corporation 0x14F2)
[2021-01-12 23:27:23.765] [debug] mpd: Disconnected: enabled interval timer.
[2021-01-12 23:27:23.772] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
[2021-01-12 23:27:23.790] [debug] GTK widget tree:
window#waybar.background.eDP-1.:dir(ltr)
  decoration:dir(ltr)
  box.horizontal:dir(ltr)
    box.horizontal.modules-left:dir(ltr)
      widget:dir(ltr)
        box#tags.horizontal:dir(ltr)
          button.flat.text-button.focused.occupied:dir(ltr)
            label:dir(ltr)
          button.flat.text-button.occupied:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
          button.flat.text-button:dir(ltr)
            label:dir(ltr)
    box.horizontal.modules-center:dir(ltr)
    box.horizontal.modules-right:dir(ltr)
      widget:dir(ltr)
        label#mpd:dir(ltr)
      widget:dir(ltr)
        label#idle_inhibitor:dir(ltr)
      widget:dir(ltr)
        label#pulseaudio:dir(ltr)
      widget:dir(ltr)
        label#network:dir(ltr)
      widget:dir(ltr)
        label#cpu:dir(ltr)
      widget:dir(ltr)
        label#memory:dir(ltr)
      widget:dir(ltr)
        label#temperature:dir(ltr)
      widget:dir(ltr)
        label#backlight:dir(ltr)
      widget:dir(ltr)
        label#battery:dir(ltr)
      widget:dir(ltr)
        label#clock:dir(ltr)
      widget:dir(ltr)
        box#tray.horizontal:dir(ltr)

[2021-01-12 23:27:23.915] [info] Bar configured (width: 1920, height: 23) for output: eDP-1
[2021-01-12 23:27:24.768] [debug] mpd: Connected to MPD
[2021-01-12 23:27:24.769] [debug] mpd: Disconnected: disabled interval timer.
[2021-01-12 23:27:24.769] [debug] mpd: Stopped: enabled 200 ms periodic timer.
[2021-01-12 23:27:24.971] [debug] mpd: Stopped: disabled 200 ms periodic timer.
[2021-01-12 23:27:24.971] [debug] mpd: Idle: watching FD
zsh: segmentation fault (core dumped)  waybar --log-level trace
```

### PR DESCRIPTION
**Pull request by euclio**
Fixes #973.

### CODE REVIEW

File: src/modules/idle_inhibitor.cpp [hunk 1]
```diff
@@ -10,8 +10,13 @@ waybar::modules::IdleInhibitor::IdleInhibitor(const std::string& id, const Bar&
                                               const Json::Value& config)
     : ALabel(config, "idle_inhibitor", id, "{status}"),
       bar_(bar),
+      idle_inhibit_manager_(waybar::Client::inst()->idle_inhibit_manager),
       idle_inhibitor_(nullptr),
       pid_(-1) {
+  if (idle_inhibit_manager_ == nullptr) {
```
Comment (Alexays) [inline src/modules/idle_inhibitor.cpp:16]: I prefer to check directly `waybar::Client::inst()->idle_inhibit_manager` rather than creating another variable

Comment (euclio) [reply src/modules/idle_inhibitor.cpp]: Fixed.

**Review by Alexays — APPROVED** [review]

**Comment by Alexays** [comment]
Thanks!
